### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by rbeysembaev** [vdomah/oc-translatetabs#4]
OctoberCMS Build 468
Translate Plugin v1.6.7

I tried to use your plugin, but got the following error:

```
Trying to access array offset on value of type null

plugins/vdomah/translatetabs/formwidgets/Translations.php line 63

$this->vars['locale'] = $this->formField->attributes['field']['locale'];
```

My fields.yaml file is super basic:
```
fields:
  _translations:
    span: left
    type: translations
    form:
      fields:
        name:
          label: Name
          span: auto
          type: text
```

Also, I couldn't find where the locale variable is even used. Commenting out the line doesn't seem to break anything (but it makes the error go away).
